# redis (dragonfly)

version: "3.8"

services:
  elysia-app:
    build: .
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.elysia-demo-app.rule=Host(`elysia-demo-app.local`)"
      # - "traefik.http.services.elysia-demo-app.loadbalancer.server.port=3000"
    networks:
      - market-network
    expose:
      - "4321"

  traefik:
    image: "traefik:3.0"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  db:
    image: bitnami/postgresql
    network:
      - market-network
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=market
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  market-network:
    external: true
